batch_size: 256
epochs: 40
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50

model:
  out_dim: 128
  base_model: "resnet50"

dataset:
  s: 1
  input_shape: (96,96,3)
  num_workers: 0
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
